name: github pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        
        with:
          dotnet-version: 7.x        
          include-prerelease: true
         
      # Publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish blazor_viz_d3_zoom.csproj -c Release -o release --nologo      
      - name: copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html      
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot          
